# aggregator-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
  labels:
    environment: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregator-service
      environment: blue
  template:
    metadata:
      labels:
        app: aggregator-service
        environment: blue
    spec:
      containers:
        - name: aggregator-service
          image: 287809004610.dkr.ecr.ap-south-1.amazonaws.com/aggregator-ms:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: ecr-registry