apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  labels:
    environment: blue
spec:
  replicas: 2  # Adjust based on your needs
  selector:
    matchLabels:
      app: integration-service
      environment: blue
  template:
    metadata:
      labels:
        app: integration-service
        environment: blue
    spec:
      containers:
        - name: integration-service
          image: 287809004610.dkr.ecr.ap-south-1.amazonaws.com/integration-ms:latest  # ECR image URL
          ports:
            - containerPort: 5001  # Replace with the port your service is listening on
          env:
            - name: DB_HOST
              value: "mooninsurance-db.czwuqysi8tph.ap-south-1.rds.amazonaws.com"  # Replace with your RDS endpoint
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Reference to the secret you created
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Reference to the secret for password
                  key: password
            - name: DB_NAME
              value: "mooninsurance-db"  # Your DB name
      imagePullSecrets:
        - name: ecr-registry