apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  labels:
    environment: blue  # Add a label to identify the Blue environment
spec:
  replicas: 2  # Adjust based on your needs
  selector:
    matchLabels:
      app: agent-service
      environment: blue  # Make sure the selector matches the environment label
  template:
    metadata:
      labels:
        app: agent-service
        environment: blue  # Add label for Blue environment
    spec:
      containers:
        - name: agent-service
          image: 287809004610.dkr.ecr.ap-south-1.amazonaws.com/agent-ms:latest  # ECR image URL
          ports:
            - containerPort: 5000  # Replace with the port your service is listening on
      imagePullSecrets:
        - name: ecr-registry