apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2  # Adjust based on your needs
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: 287809004610.dkr.ecr.ap-south-1.amazonaws.com/notification-service:latest  # ECR image URL
          ports:
            - containerPort: 5002  # Replace with the port your service is listening on
