apiVersion: v1
kind: Service
metadata:
  name: agent-service
  labels:
    environment: green
spec:
  selector:
    app: agent-service
    environment: green
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
