# aggregator-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  labels:
    environment: green
spec:
  selector:
    app: aggregator-service
    environment: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
