apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-green
  labels:
    environment: green
spec:
  replicas: 2  # Adjust based on your needs
  selector:
    matchLabels:
      app: notification-service
      environment: green
  template:
    metadata:
      labels:
        app: notification-service
        environment: green
    spec:
      containers:
        - name: notification-service
          image: 287809004610.dkr.ecr.ap-south-1.amazonaws.com/notification-ms:latest  # ECR image URL
          ports:
            - containerPort: 5002  # Replace with the port your service is listening on
      imagePullSecrets:
        - name: ecr-registry