apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    environment: blue
spec:
  selector:
    app: notification-service
    environment: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: LoadBalancer
