# aggregator-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  labels:
    environment: blue
spec:
  selector:
    app: aggregator-service
    environment: blue
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
