# aggregator-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
        - name: aggregator-service
          image: 287809004610.dkr.ecr.ap-south-1.amazonaws.com/aggregator-service:latest
          ports:
            - containerPort: 5000
