name: CI/CD Pipeline

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build, Tag, and Push Docker Images
        run: |
          declare -A services=( 
            ["Agent_MS"]="agent-ms" 
            ["Integration_MS"]="integration-ms" 
            ["Notification_MS"]="notification-ms" 
            ["Aggregator_MS"]="aggregator-ms" 
          )

          for folder in "${!services[@]}"; do
            image_name=${services[$folder]}
            echo "🔧 Building image: $image_name from folder: $folder"

            docker build -t $image_name ./$folder
            docker tag $image_name:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$image_name:latest
            docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$image_name:latest
          done

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name mooninsurance-cluster

      # Step 1: Deploy to Blue Environment
      - name: Deploy to Blue Environment
        run: |
          kubectl apply -f k8s/deployment/blue/
          kubectl apply -f k8s/service/blue/

      # Step 2: Deploy to Green Environment
      - name: Deploy to Green Environment
        run: |
          # Delete existing green deployments before applying new ones
          kubectl delete deployment agent-service-green || true
          kubectl delete deployment integration-service-green || true
          kubectl delete deployment notification-service-green || true
          kubectl delete deployment aggregator-service-green || true


          kubectl apply -f k8s/deployment/green/
          kubectl apply -f k8s/service/green/

      # Step 3: Run Integration Tests
      - name: Run Integration Tests
        run: |
          echo "Running integration tests..."

          SERVICES=("agent-service" "integration-service" "notification-service" "aggregator-service")
          URLS=()

          for svc in "${SERVICES[@]}"; do
            echo "Checking LoadBalancer for $svc..."
            url=""
            while [ -z "$url" ]; do
              echo "Waiting for $svc LoadBalancer IP..."
              sleep 10
              url=$(kubectl get svc "$svc" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            done
            echo "$svc is available at $url"
            URLS+=("$url")
          done

          AGENT_SERVICE_URL=${URLS[0]}
          INTEGRATION_SERVICE_URL=${URLS[1]}
          NOTIFICATION_SERVICE_URL=${URLS[2]}
          AGGREGATOR_SERVICE_URL=${URLS[3]}

          echo "Testing /health endpoints..."

          curl --fail "http://$AGENT_SERVICE_URL/health" || exit 1
          curl --fail "http://$INTEGRATION_SERVICE_URL/health" || exit 1
          curl --fail "http://$NOTIFICATION_SERVICE_URL/health" || exit 1
          curl --fail "http://$AGGREGATOR_SERVICE_URL/health" || exit 1

          echo "All services are healthy."

      # Step 4: Switch Traffic to Green Environment (Blue-Green Switch)
      - name: Switch Traffic to Green
        run: |
          kubectl apply -f k8s/service/green/service-agent.yaml
          kubectl apply -f k8s/service/green/service-integration.yaml
          kubectl apply -f k8s/service/green/service-notification.yaml
          kubectl apply -f k8s/service/green/service-aggregator.yaml

      # Step 5: Clean up Blue Environment (Optional)
      - name: Clean Up Blue Environment (Optional)
        run: |
          kubectl delete deployment agent-service --selector=environment=blue
          kubectl delete deployment integration-service --selector=environment=blue
          kubectl delete deployment notification-service --selector=environment=blue
          kubectl delete deployment aggregator-service --selector=environment=blue
